import React from "react";
import logo from "./assets/SFSF.png";

const navItems = [
  { label: "Infrastructure", href: "/infrastructure" },
  { label: "Case Studies", href: "/case-studies" },
  { label: "About", href: "/about" },
  { label: "Contact", href: "/contact" },
];

const pageStyle = "min-h-screen bg-[#fbf6e8] text-[#111111] font-sans";
const shell = "mx-auto w-full max-w-[1200px] px-6 py-8 md:px-10";
const card = "rounded-3xl border border-[#111111]/15 bg-white/70 shadow-[0_10px_30px_rgba(17,17,17,0.08)]";

function Header({ activePage, showCTA = true }) {
  return (
    <header className="mb-10 flex items-center justify-between gap-6">
      <a href="/" className="flex items-center"><img src={logo} alt="SFS" className="h-10 w-auto" /></a>
      <nav className="hidden items-center gap-8 md:flex text-sm">
        {navItems.map((item) => (
          <a key={item.label} href={item.href} className={activePage === item.href ? "text-[#0b8f68] border-b border-[#0b8f68] pb-1" : "text-[#111111]"}>{item.label}</a>
        ))}
      </nav>
      {showCTA && <a href="/contact" className="rounded-xl bg-[#0b8f68] px-5 py-3 text-sm font-semibold text-white">Book Your Assessment</a>}
    </header>
  );
}

function Footer() { return <footer className="mt-12 border-t border-[#111111]/15 pt-8"><div className="grid gap-6 md:grid-cols-3 items-start"><img src={logo} alt="SFS" className="h-10" /><p className="text-sm text-[#333]">We build and manage mission-critical communication infrastructure that drives real-world results.</p><div className="space-y-2"><label className="text-sm">Newsletter signup</label><div className="flex gap-2"><input className="w-full rounded-lg border border-[#111111]/20 bg-white px-3 py-2 text-sm" placeholder="Email address" /><button className="rounded-lg bg-[#0b8f68] px-4 py-2 text-white">Join</button></div><div className="flex gap-4 text-sm"><a href="#">Terms</a><a href="#">Privacy</a></div></div></div></footer>; }

function CTASection({ headline, eyebrow, buttonLabel, href }) { return <section className={`${card} mt-10 flex flex-col gap-4 p-8 md:flex-row md:items-center md:justify-between`}><div><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">{eyebrow}</p><h3 className="font-serif text-4xl">{headline}</h3></div><a href={href} className="rounded-xl bg-[#0b8f68] px-5 py-3 text-sm font-semibold text-white">{buttonLabel}</a></section>; }

function AssessmentSummaryCard() { return <div className={`${card} p-6`}><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">Assessment Summary</p><div className="mt-4 space-y-3 text-sm"><Row label="Audience Reactivation Potential" value="83%" /><Row label="Reachable Contacts" value="246K" /><Row label="Dormant Revenue" value="$3.8M" /><Row label="Data Health" value="78%" /><Row label="Ready to Reactivate" value="Yes" /></div></div>; }
const Row = ({ label, value }) => <div className="flex justify-between border-b border-[#111111]/10 pb-2"><span className="text-[#4a4a4a]">{label}</span><span className="font-semibold">{value}</span></div>;

function SystemDiagram() { const nodes=(t)=> <div className="rounded-xl border border-[#111111]/15 bg-white p-3 text-sm">{t}</div>; return <div className={`${card} p-6`}><div className="grid grid-cols-3 items-center gap-4"><div className="space-y-3">{["CRM","Historical Engagement","Compliance Data","Audience Records"].map(nodes)}</div><div className="rounded-2xl border border-[#0b8f68]/30 p-6 text-center font-semibold">Unified Data System</div><div className="space-y-3">{["Email","SMS","Voice","Direct Mail"].map(nodes)}</div></div></div>; }

function FeatureCard({ title, description }) { return <article className={`${card} p-5`}><h4 className="font-serif text-2xl">{title}</h4><p className="mt-2 text-sm text-[#333]">{description}</p></article>; }
function TrustedLogoBar() { const names=["Stanford University","City of Concord","Drew Medical","Roux","DGRP","Parade of Youth","The Anthemist","D55","PG&E"]; return <section className={`${card} p-6`}><h3 className="text-center text-xs uppercase tracking-[0.2em] text-[#0b8f68]">Trusted by organizations that lead</h3><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-5">{names.map((n,i)=><div key={n} className="text-center text-[#4a4a4a]" style={{fontWeight:[400,700,500,300,600,400,500,700,600][i],letterSpacing:["0","0.14em","0.06em","0.1em","0","0.08em","0.03em","0.02em","0"][i]}}>{n}</div>)}</div></section>; }
function CaseStudyCard({ sector,title,quote,m1,m2 }) { return <article className={`${card} p-5`}><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">{sector}</p><h4 className="mt-2 font-serif text-3xl">{title}</h4><p className="mt-3 text-sm text-[#333]">“{quote}”</p><div className="mt-3 flex gap-2"><span className="rounded-lg border border-[#111111]/15 px-3 py-1 text-sm">{m1}</span><span className="rounded-lg border border-[#111111]/15 px-3 py-1 text-sm">{m2}</span></div><a href="#" className="mt-4 inline-block text-sm text-[#0b8f68]">View case study</a></article>; }

function BookingForm(){return <form className={`${card} p-6 space-y-4`}><div className="grid gap-3 md:grid-cols-2">{["First name","Last name"].map(p=><input key={p} placeholder={p} className="rounded-lg border border-[#111111]/20 bg-white px-3 py-2"/>)}</div>{["Work email","Company / Organization","Role","Program focus","Monthly send volume"].map(p=><input key={p} placeholder={p} className="w-full rounded-lg border border-[#111111]/20 bg-white px-3 py-2"/>)}<textarea placeholder="Goals and current challenges" className="h-28 w-full rounded-lg border border-[#111111]/20 bg-white px-3 py-2"/><button className="rounded-xl bg-[#0b8f68] px-5 py-3 text-sm font-semibold text-white">Book Your Assessment</button></form>}
function WhatToExpectPanel(){const s=[["01","Share your details","Tell us about your program, goals, and current challenges."],["02","We review","Our team reviews your information and prepares tailored insights."],["03","Let’s connect","We schedule your assessment and map the right next steps."]];return <aside className={`${card} p-6`}><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">What to expect</p><div className="mt-4 space-y-4">{s.map(([n,t,d])=><div key={n}><p className="text-2xl font-serif text-[#0b8f68]">{n}</p><p className="font-semibold">{t}</p><p className="text-sm text-[#333]">{d}</p></div>)}</div></aside>}

function Home(){return <main className={pageStyle}><div className={shell}><Header activePage="/"/><section className="grid gap-8 md:grid-cols-2 items-start"><div><p className="text-xs uppercase tracking-[0.24em] text-[#0b8f68]">Data. Infrastructure. Results.</p><h1 className="mt-4 font-serif text-6xl leading-tight">Your database, reactivated.</h1><p className="mt-5 text-lg text-[#333]">We build, deploy, and manage the communication infrastructure that turns dormant connections into qualified, engaged audiences.</p><a href="/contact" className="mt-6 inline-block rounded-xl bg-[#0b8f68] px-5 py-3 text-sm font-semibold text-white">Book Your Assessment</a></div><AssessmentSummaryCard/></section><section className="mt-10 text-center"><h2 className="font-serif text-4xl">Built to reactivate what you already own.</h2><p className="mx-auto mt-3 max-w-3xl text-[#333]">Social Following Studios builds and manages the communication infrastructure behind dormant databases, qualified audiences, and owned-channel revenue.</p></section><CTASection eyebrow="Assessment" headline="Let’s put your database to work." buttonLabel="Book Your Assessment" href="/contact"/><Footer/></div></main>}

function Infrastructure(){const features=[ ["Unified Database","Every contact record, engagement signal, and compliance flag lives in one structured layer. Your program pulls from a single source of truth across every channel."],["Rules Engine","Automated logic governs who receives what message, when, and through which channel. Compliance requirements, suppression lists, and engagement thresholds execute without manual intervention."],["Channel Orchestration","Email, SMS, voice, and direct mail route through one coordinated system. Sequence timing, channel priority, and fallback logic run from a single configuration."],["Real-time Monitoring","Delivery performance, inbox placement rates, and engagement signals surface continuously. Program adjustments happen inside the active send window, not after the report."]];return <main className={pageStyle}><div className={shell}><Header activePage="/infrastructure"/><h1 className="font-serif text-6xl">One system. Every channel.</h1><p className="mt-4 max-w-3xl text-[#333]">A unified infrastructure that connects your data, governs every decision, and delivers coordinated outreach across every channel.</p><a href="/contact" className="mt-6 inline-block rounded-xl bg-[#0b8f68] px-5 py-3 text-sm font-semibold text-white">Book Your Assessment</a><div className="mt-8"><SystemDiagram/></div><section className={`${card} mt-8 p-6`}><h3 className="font-serif text-3xl">Build</h3><p className="mt-2 text-[#333]">We construct the delivery infrastructure your program runs on: authentication, list architecture, rules engine, and channel orchestration unified into one managed system.</p></section><section className="mt-8 grid gap-4 md:grid-cols-2">{features.map(([t,d])=><FeatureCard key={t} title={t} description={d}/> )}</section><section className="mt-8"><p className="text-center text-xs uppercase tracking-[0.2em] text-[#0b8f68]">How It Works</p><div className="mt-4 grid gap-4 md:grid-cols-4">{[["01","Ingest","We intake your existing contact data, historical engagement records, and compliance documentation into a structured database with clean field mapping and deduplication."],["02","Process","We apply segmentation logic, suppression rules, and compliance filters so every record carries the correct status before any message generates."],["03","Evaluate","We run deliverability diagnostics across your sending domains, authentication records, and IP reputation to establish a clean baseline for deployment."],["04","Engage","We activate coordinated outreach across your configured channels with full monitoring from the first send."]].map(([n,t,d])=><div key={n} className={`${card} p-4`}><p className="font-serif text-3xl text-[#0b8f68]">{n}</p><h4 className="font-semibold">{t}</h4><p className="text-sm text-[#333]">{d}</p></div>)}</div></section><CTASection eyebrow="Infrastructure" headline="Let’s build the infrastructure that drives results." buttonLabel="Book Your Assessment" href="/contact"/><Footer/></div></main>}

function CaseStudies(){return <main className={pageStyle}><div className={shell}><Header activePage="/case-studies"/><h1 className="font-serif text-6xl">Results from real engagements.</h1><p className="mt-4 max-w-3xl text-[#333]">See how organizations use SFS to reactivate dormant connections, strengthen communication infrastructure, and produce measurable outcomes.</p><section className={`${card} mt-8 p-6`}><div className="flex items-center justify-between"><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">Featured Case Study</p><span className="rounded-full bg-[#0b8f68]/10 px-3 py-1 text-sm">Infrastructure in place</span></div><h3 className="mt-3 font-serif text-4xl">National Environmental Nonprofit</h3><p className="mt-3 text-lg italic text-[#333]">“Social Following Studios built the foundation that allows us to connect with the right audiences and inspire action at scale.”</p><div className="mt-4 grid gap-3 md:grid-cols-4">{["172% increase in engaged audience","318K reachable contacts","$2.6M dormant revenue","96% data health"].map((m)=><div key={m} className="rounded-xl border border-[#111111]/15 p-3 text-sm">{m}</div>)}</div></section><div className="mt-8"><TrustedLogoBar/></div><section className="mt-8 grid gap-4 md:grid-cols-2 lg:grid-cols-4"><CaseStudyCard sector="Nonprofit" title="Youth Arts Organization" quote="Their team helped us turn outreach into meaningful relationships." m1="146% recurring donors" m2="2.3x email engagement"/><CaseStudyCard sector="Healthcare" title="Regional Health System" quote="We now have infrastructure to communicate with patients in timely ways." m1="61% patient re-engagement" m2="3.8M monthly messages"/><CaseStudyCard sector="Association" title="Professional Association" quote="Better data, smarter outreach, stronger member connections." m1="85% renewals retained" m2="47% event registrations"/><CaseStudyCard sector="B2B Services" title="B2B Technology Provider" quote="SFS built a scalable system that keeps our teams aligned." m1="2.1x pipeline" m2="34% SQL increase"/></section><CTASection eyebrow="Proof" headline="Ready to build results like these?" buttonLabel="Book Your Assessment" href="/contact"/><Footer/></div></main>}

function Contact(){return <main className={pageStyle}><div className={shell}><Header activePage="/contact"/><h1 className="font-serif text-6xl">Book your assessment.</h1><p className="mt-4 max-w-3xl text-[#333]">Tell us about your program and goals. We’ll review your details and reach out with next steps.</p><section className="mt-8 grid gap-4 md:grid-cols-[2fr_1fr]"><BookingForm/><WhatToExpectPanel/></section><section className="mt-8"><p className="text-center text-xs uppercase tracking-[0.2em] text-[#0b8f68]">Other Ways To Connect</p><div className="mt-4 grid gap-4 md:grid-cols-3">{[["Email Us","hello@socialfollowingstudios.com"],["Call Us","(833) 980-7261"],["Schedule a Time","View Calendar"]].map(([t,d])=><div key={t} className={`${card} p-5`}><h4 className="font-serif text-3xl">{t}</h4><p className="mt-2 text-sm text-[#333]">{d}</p></div>)}</div></section><section className={`${card} mt-8 p-5`}><p className="text-xs uppercase tracking-[0.2em] text-[#0b8f68]">Next Steps</p><div className="mt-2 grid gap-2 md:grid-cols-3 text-sm"><p>Book your assessment</p><p>We’ll confirm</p><p>Let’s get to work</p></div></section><CTASection eyebrow="Assessment" headline="Let’s put your database to work." buttonLabel="Book Your Assessment" href="/contact"/><Footer/></div></main>}

function About(){return <main className={pageStyle}><div className={shell}><Header activePage="/about"/><section className={`${card} p-8`}><h1 className="font-serif text-5xl">About Social Following Studios</h1><p className="mt-4 text-[#333]">We design and operate communication infrastructure that helps organizations reactivate and grow owned audiences.</p></section><Footer/></div></main>}

export default function App() {
  const path = window.location.pathname.toLowerCase();
  if (path === "/infrastructure") return <Infrastructure />;
  if (path === "/case-studies") return <CaseStudies />;
  if (path === "/contact") return <Contact />;
  if (path === "/about") return <About />;
  return <Home />;
}
